// Elementlarni olish
const registerForm = document.getElementById(
  "registerForm"
) as HTMLFormElement | null;
const nameInput = document.getElementById("regName") as HTMLInputElement | null;
const emailInput = document.getElementById(
  "regEmail"
) as HTMLInputElement | null;
const passwordInput = document.getElementById(
  "regPassword"
) as HTMLInputElement | null;

let emailError = document.getElementById(
  "regEmailError"
) as HTMLDivElement | null;
let passwordError = document.getElementById(
  "regPasswordError"
) as HTMLDivElement | null;

if (emailInput && !emailError) {
  emailError = document.createElement("div");
  emailError.id = "regEmailError";
  emailError.style.color = "red";
  emailError.style.fontSize = "0.95em";
  emailInput.insertAdjacentElement("afterend", emailError);
}

if (passwordInput && !passwordError) {
  passwordError = document.createElement("div");
  passwordError.id = "regPasswordError";
  passwordError.style.color = "red";
  passwordError.style.fontSize = "0.95em";
  passwordInput.insertAdjacentElement("afterend", passwordError);
}

// Email tekshirish funksiyasi
function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

// Parol tekshirish funksiyasi
function isValidPassword(password: string): boolean {
  return /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{8,}$/.test(password);
}

// Parol generator funksiyasi
function generatePassword(length: number = 10): string {
  const chars =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-={}[]|:;<>,.?/~";
  let password = "";
  for (let i = 0; i < length; i++) {
    password += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return password;
}

// Parol input validatsiya funksiyasi (alohida funksiya sifatida)
function validatePasswordInput() {
  if (passwordInput && passwordError) {
    if (!passwordInput.value) {
      passwordError.textContent = "";
    } else if (!isValidPassword(passwordInput.value)) {
      passwordError.textContent =
        "Parol kamida 8 ta belgidan iborat, kamida 1 ta harf va 1 ta raqam bo'lishi kerak!";
    } else {
      passwordError.textContent = "";
    }
  }
}

// Email input validatsiya funksiyasi (alohida funksiya sifatida)
function validateEmailInput() {
  if (emailInput && emailError) {
    if (!emailInput.value) {
      emailError.textContent = "";
    } else if (!isValidEmail(emailInput.value)) {
      emailError.textContent = "Email noto'g'ri kiritilgan!";
    } else {
      emailError.textContent = "";
    }
  }
}

// Email input validatsiya
if (emailInput && emailError) {
  emailInput.addEventListener("input", validateEmailInput);
}

// Parol input validatsiya
if (passwordInput && passwordError) {
  passwordInput.addEventListener("input", validatePasswordInput);
}

// Parol ko‘rsatish/tushirish
const togglePasswordBtn = document.getElementById(
  "togglePassword"
) as HTMLButtonElement | null;
if (togglePasswordBtn && passwordInput) {
  togglePasswordBtn.addEventListener("click", () => {
    if (passwordInput.type === "password") {
      passwordInput.type = "text";
      togglePasswordBtn.innerHTML = '<i class="fa fa-eye-slash"></i>';
    } else {
      passwordInput.type = "password";
      togglePasswordBtn.innerHTML = '<i class="fa fa-eye"></i>';
    }
  });
}

// Modal elementlar
const autoPasswordModal = document.getElementById(
  "autoPasswordModal"
) as HTMLElement | null;
const acceptAutoPassword = document.getElementById(
  "acceptAutoPassword"
) as HTMLButtonElement | null;
const declineAutoPassword = document.getElementById(
  "declineAutoPassword"
) as HTMLButtonElement | null;

let autoGeneratedPassword = "";

// Automate password generation
if (passwordInput) {
  passwordInput.addEventListener("focus", () => {
    if (!passwordInput.value) {
      autoGeneratedPassword = generatePassword(10);
      passwordInput.value = autoGeneratedPassword;
      if (passwordError) passwordError.textContent = "";
      // Avtomatik generatsiya qilinganda validatsiya ham tekshiriladi
      validatePasswordInput();
      if (autoPasswordModal) {
        // @ts-ignore
        const modal = new bootstrap.Modal(autoPasswordModal);
        modal.show();
      }
    }
  });
}

// Modal tugmalari
acceptAutoPassword?.addEventListener("click", () => {
  // hech narsa qilmaymiz
});

declineAutoPassword?.addEventListener("click", () => {
  if (passwordInput) {
    passwordInput.value = "";
    autoGeneratedPassword = "";
    validatePasswordInput();
  }
});

// Error elementlarga class berish
emailError?.classList.add("text-danger");
passwordError?.classList.add("text-danger");

// Formani submit qilish
if (registerForm && nameInput && emailInput && passwordInput) {
  registerForm.addEventListener("submit", function (e) {
    e.preventDefault();

    const name = nameInput.value.trim();
    const email = emailInput.value.trim();
    const password = passwordInput.value;

    let valid = true;

    if (!name) {
      alert("Ismni kiriting!");
      nameInput.focus();
      valid = false;
    }

    if (!isValidEmail(email)) {
      if (emailError) emailError.textContent = "Email noto'g'ri kiritilgan!";
      emailInput.focus();
      valid = false;
    } else {
      if (emailError) emailError.textContent = "";
    }

    if (!isValidPassword(password)) {
      if (passwordError)
        passwordError.textContent =
          "Parol kamida 8 ta belgidan iborat, kamida 1 ta harf va 1 ta raqam bo'lishi kerak!";
      passwordInput.focus();
      valid = false;
    } else {
      if (passwordError) passwordError.textContent = "";
    }

    if (!valid) return;

    console.log({ name, email, password });
    alert("Ro'yxatdan muvaffaqiyatli o'tdingiz!");
    registerForm.reset();
    if (emailError) emailError.textContent = "";
    if (passwordError) passwordError.textContent = "";
  });
}

// Forma reset tugmasi
const resetForm = document.getElementById(
  "resetForm"
) as HTMLButtonElement | null;
resetForm?.addEventListener("click", () => {
  registerForm?.reset();
  if (emailError) emailError.textContent = "";
  if (passwordError) passwordError.textContent = "";
  nameInput?.focus();
});
